### ISSUE TITLE
Can not work with cobertura under JDK 7 environment

### ISSUE THREAD

**Issue by henri-tremblay** [easymock/easymock#140]
*Migrated from:* CodeHaus issue EASYMOCK-129
*Original reporter:* Daniel Liu

---------------------------------------------------------
cobertura 2 is using CGlib 3 under JDK 7 environment, which is not compatible with EasyMock 3.2 ( because EasyMock 3.2 is using CGlib 2)

**Comment by henri-tremblay** [comment]
*Original comment author:* Henri Tremblay

---------------------------------------------------------
Can you give me some details? Does it mean that CGlib 3 would work?

Do you have an example of a failing project?

What is the error?

Isn't it a problem on the Cobertura side? Cobertura used to crash also with Spring. Which is why EasyMock use Clover. Jacoco also works.

**Comment by henri-tremblay** [comment]
*Original comment author:* Daniel Liu

---------------------------------------------------------
I have tried CGlib 3. it doesn't work.

Here I give you some stack trace log and jar list like below.

As you can see, the updated jars are only asm, cglib, easymock libs.


    [junit] Testcase: testGetContractSummary took 0.175 sec
    [junit] 	Caused an ERROR
    [junit] net/sf/cglib/asm/util/TraceClassVisitor
    [junit] java.lang.NoClassDefFoundError: net/sf/cglib/asm/util/TraceClassVisitor
    [junit] 	at net.sf.cglib.core.DebuggingClassWriter.toByteArray(DebuggingClassWriter.java:73)
    [junit] 	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:26)
    [junit] 	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
    [junit] 	at net.sf.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144)
    [junit] 	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:116)
    [junit] 	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:108)
    [junit] 	at net.sf.cglib.core.KeyFactory.create(KeyFactory.java:104)
    [junit] 	at net.sf.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
    [junit] 	at org.easymock.internal.ClassProxyFactory.createEnhancer(ClassProxyFactory.java:257)
    [junit] 	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:165)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:114)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:88)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:79)
    [junit] 	at org.easymock.EasyMock.createMock(EasyMock.java:136)
    [junit] 	at com.ContractSummaryDomainManagerImplTest.setUp(ContractSummaryDomainManagerImplTest.java:66)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:601)
    [junit] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    [junit] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    [junit] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    [junit] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
    [junit] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    [junit] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    [junit] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    [junit] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    [junit] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    [junit] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:768)
    [junit] Caused by: java.lang.ClassNotFoundException: net.sf.cglib.asm.util.TraceClassVisitor
    [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    [junit] 	at java.security.AccessController.doPrivileged(Native Method)
    [junit] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    [junit] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    [junit] 	... 36 more
    [junit] 
    [junit] Testcase: testDeleteContractSummary took 0 sec
    [junit] 	Caused an ERROR
    [junit] Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] java.lang.NoClassDefFoundError: Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] 	at org.easymock.internal.ClassProxyFactory.createEnhancer(ClassProxyFactory.java:257)
    [junit] 	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:165)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:114)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:88)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:79)
    [junit] 	at org.easymock.EasyMock.createMock(EasyMock.java:136)
    [junit] 	at com.ContractSummaryDomainManagerImplTest.setUp(ContractSummaryDomainManagerImplTest.java:66)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:601)
    [junit] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    [junit] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    [junit] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    [junit] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
    [junit] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    [junit] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    [junit] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    [junit] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    [junit] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    [junit] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:768)
    [junit] 
    [junit] Testcase: testCreateContractSummary took 0 sec
    [junit] 	Caused an ERROR
    [junit] Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] java.lang.NoClassDefFoundError: Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] 	at org.easymock.internal.ClassProxyFactory.createEnhancer(ClassProxyFactory.java:257)
    [junit] 	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:165)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:114)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:88)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:79)
    [junit] 	at org.easymock.EasyMock.createMock(EasyMock.java:136)
    [junit] 	at com.ContractSummaryDomainManagerImplTest.setUp(ContractSummaryDomainManagerImplTest.java:66)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:601)
    [junit] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    [junit] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    [junit] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    [junit] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
    [junit] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    [junit] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    [junit] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    [junit] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    [junit] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    [junit] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:768)
    [junit] 
    [junit] Testcase: testUpdateContractSummary took 0 sec
    [junit] 	Caused an ERROR
    [junit] Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] java.lang.NoClassDefFoundError: Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] 	at org.easymock.internal.ClassProxyFactory.createEnhancer(ClassProxyFactory.java:257)
    [junit] 	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:165)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:114)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:88)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:79)
    [junit] 	at org.easymock.EasyMock.createMock(EasyMock.java:136)
    [junit] 	at com.ContractSummaryDomainManagerImplTest.setUp(ContractSummaryDomainManagerImplTest.java:66)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:601)
    [junit] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    [junit] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    [junit] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    [junit] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
    [junit] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    [junit] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    [junit] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    [junit] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    [junit] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    [junit] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:768)
    [junit] 
    [junit] Testcase: testGetContractSummaryNullReturn took 0 sec
    [junit] 	Caused an ERROR
    [junit] Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] java.lang.NoClassDefFoundError: Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] 	at org.easymock.internal.ClassProxyFactory.createEnhancer(ClassProxyFactory.java:257)
    [junit] 	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:165)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:114)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:88)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:79)
    [junit] 	at org.easymock.EasyMock.createMock(EasyMock.java:136)
    [junit] 	at com.ContractSummaryDomainManagerImplTest.setUp(ContractSummaryDomainManagerImplTest.java:66)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:601)
    [junit] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    [junit] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    [junit] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    [junit] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
    [junit] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    [junit] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    [junit] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    [junit] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    [junit] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    [junit] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:768)
    [junit] 
    [junit] Testcase: testCreateUpdateContractSummaryWithValidationException_NotConsistent took 0 sec
    [junit] 	Caused an ERROR
    [junit] Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] java.lang.NoClassDefFoundError: Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] 	at org.easymock.internal.ClassProxyFactory.createEnhancer(ClassProxyFactory.java:257)
    [junit] 	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:165)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:114)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:88)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:79)
    [junit] 	at org.easymock.EasyMock.createMock(EasyMock.java:136)
    [junit] 	at com.ContractSummaryDomainManagerImplTest.setUp(ContractSummaryDomainManagerImplTest.java:66)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:601)
    [junit] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    [junit] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    [junit] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    [junit] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
    [junit] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    [junit] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    [junit] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    [junit] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    [junit] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    [junit] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:768)
    [junit] 
    [junit] Testcase: testCreateUpdateContractSummaryWithValidationException_StartAfterEnd took 0 sec
    [junit] 	Caused an ERROR
    [junit] Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] java.lang.NoClassDefFoundError: Could not initialize class org.easymock.internal.ClassProxyFactory$2
    [junit] 	at org.easymock.internal.ClassProxyFactory.createEnhancer(ClassProxyFactory.java:257)
    [junit] 	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:165)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:114)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:88)
    [junit] 	at org.easymock.internal.MocksControl.createMock(MocksControl.java:79)
    [junit] 	at org.easymock.EasyMock.createMock(EasyMock.java:136)
    [junit] 	at com.ContractSummaryDomainManagerImplTest.setUp(ContractSummaryDomainManagerImplTest.java:66)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [junit] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    [junit] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [junit] 	at java.lang.reflect.Method.invoke(Method.java:601)
    [junit] 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    [junit] 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    [junit] 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    [junit] 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:27)
    [junit] 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)
    [junit] 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)
    [junit] 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
    [junit] 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
    [junit] 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
    [junit] 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
    [junit] 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
    [junit] 	at org.junit.runners.ParentRunner.run(ParentRunner.java:292)
    [junit] 	at junit.framework.JUnit4TestAdapter.run(JUnit4TestAdapter.java:39)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.run(JUnitTestRunner.java:420)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.launch(JUnitTestRunner.java:911)
    [junit] 	at org.apache.tools.ant.taskdefs.optional.junit.JUnitTestRunner.main(JUnitTestRunner.java:768)

activation-1.1.1.jar
ant-1.7.1.jar
ant-contrib-1.0b2.jar
asm-2.2.1.jar--
asm-4.1.jar
asm-analysis-4.1.jar
asm-commons-4.1.jar
asm-tree-2.2.1.jar--
asm-tree-4.1.jar
asm-util-4.1.jar
cglib-nodep-2.2.2.jar--
cglib-nodep-3.0.jar
cobertura-2.0.3.jar
commons-codec-1.8.jar
commons-collections-3.2.1.jar
commons-dbcp-1.4.jar
commons-httpclient-3.1.jar
commons-lang-2.6.jar
commons-logging-1.1.1.jar
commons-pool-1.5.4.jar
dom4j-1.6.1.jar
easymock-2.4.jar--
easymock-3.2.jar
easymockclassextension-2.4.jar--
easymockclassextension-3.2.jar
freemarker-2.3.15.jar
geoip-1.2.5.jar
hamcrest-core-1.1.jar
hsqldb-1.8.0.1.jar
ibatis-sqlmap-2.3.4.726.jar
icu4j-2.6.1.jar
jaxb-api-2.0.jar
jaxb-impl-2.0.1.jar
jaxb-xjc-2.0.1.jar
jaxen-1.1-beta-8.jar
jaxen-1.1.4.jar
jboss-common-core-2.2.10.GA.jar
jboss-logging-spi-2.0.5.GA.jar
jbosscache-core-3.0.3.GA.jar
jcl-over-slf4j-1.7.5.jar
jdom-1.0.jar
jetty-6.1.14.jar
jetty-util-6.1.14.jar
jgroups-2.6.7.GA.jar
joda-time-1.6.jar
jsr173_api-1.0.jar
jta-1.1.jar
jtds-1.3.1.jar
junit-4.9.jar
log4j-1.2.17.jar
log4mongo-java-0.7.4.jar
mail-1.4.jar
mongo-java-driver-2.11.2.jar
mvel2-2.1.5.Final.jar
objenesis-1.3.jar
ognl-2.6.9.jar
org.json-chargebee-1.0.jar
oro-2.0.8.jar
servlet-api-2.5.jar
slf4j-api-1.7.5.jar
slf4j-log4j12-1.7.5.jar
spatial-solr-2.0-RC5.jar
stax-api-1.0.1.jar
stopwatch-0.4.jar
tagsoup-0.9.7.jar
unitils-2.2.jar
wsdl4j-1.6.3.jar
wstx-asl-3.2.7.jar
xalan-2.6.0.jar
xercesImpl-2.6.2.jar
xfire-all-starcite-1.2.6.jar
xfire-jsr181-api-1.0-M1.jar
xml-apis-1.0.b2.jar
xmlParserAPIs-2.6.2.jar
XmlSchema-1.4.7.jar
xom-1.0b3.jar

**Comment by henri-tremblay** [comment]
*Original comment author:* Daniel Liu

---------------------------------------------------------
It seams the CGlib 3 somehow causes the try-catch around loading net.sf.cglib.asm.util.TraceClassVisitor not working

**Comment by henri-tremblay** [comment]
*Original comment author:* Henri Tremblay

---------------------------------------------------------
Since EasyMock is now using cglib 3.1, hopefully this will be solved.
