### ISSUE TITLE
Class mocking can't handle Java 8 class files

### ISSUE THREAD

**Issue by henri-tremblay** [easymock/easymock#151]
*Migrated from:* CodeHaus issue EASYMOCK-140
*Original reporter:* Jonas

---------------------------------------------------------
Easymock 3.3 uses cglib-nodep 3.1, which contains asm 4.2, which refuses to handle java 8 class files (version 52) (stacktrace see below).

With Easymock 3.2 (and cglib-nodep 2.2.2) this worked (probably by chance), since asm didn't refuse to handle Java 8 class files.

asm supports Java 8 in version 5. However, unfortunately there doesn't seem to be a release of cglib that uses asm 5.

**Comment by henri-tremblay** [comment]
*Original comment author:* Jonas

---------------------------------------------------------
java.lang.IllegalArgumentException
	at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
	at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
	at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
	at net.sf.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:61)
	at net.sf.cglib.proxy.Enhancer.emitMethods(Enhancer.java:911)
	at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:498)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
	at net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:175)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:129)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:103)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:94)
	at org.easymock.EasyMock.createMock(EasyMock.java:136)
	at com.KlassTest.testMethod(KlassTest.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at com.ecofin.util.junit.SelectiveTestRunner$ThrowingRunner.runChild(SelectiveTestRunner.java:114)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by henri-tremblay** [comment]
*Original comment author:* Henri Tremblay

---------------------------------------------------------
All my unit tests were working on Java 8...

But I guess you used a lambda in the class? I should have tested that :-(

As a workaround, you can downgrade cglib

**Comment by henri-tremblay** [comment]
*Original comment author:* Henri Tremblay

---------------------------------------------------------
Hi. Can you please provide a failing example?

I tried on a lambda and a lambda with closure and had no problems.

So I will need more information to reproduce

Thanks

**Comment by henri-tremblay** [comment]
*Original comment author:* Scott Carey

---------------------------------------------------------
Example:

EasyMock.createMock(File.class);


With Java 8.

I upgraded to 3.3 from 3.2 because other Java 8 classes were failing, and the problem simply switched to another place.  At least this one is easier to reproduce in a limited example.

cglib should be using the newer asm, that supports Java 8.

**Comment by henri-tremblay** [comment]
*Original comment author:* Scott Carey

---------------------------------------------------------
I have confirmed that if I exclude cglib-nodeps from my build, then manually add cglib 3.1 and asm 5.0.3 it works.

So the root problem is cglib, the proxy is easyMock, which could have a -nodeps variant that bundles cglib and asm 5.0.3 in its own namespace.

**Comment by henri-tremblay** [comment]
*Original comment author:* Scott Carey

---------------------------------------------------------
I suspect it is default methods, not closures that are the problem.  But I'm not going to dig into this in detail.   It could also only happen in more complicated situations -- the places I have seen it are all very large classes.

**Comment by henri-tremblay** [comment]
*Original comment author:* Scott Carey

---------------------------------------------------------
For what its worth, I get the error above with EasyMock 3.3, and with 3.2 I get:

java.lang.ArrayIndexOutOfBoundsException: 29274
	at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
	at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
	at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
	at net.sf.cglib.asm.ClassReader.<init>(Unknown Source)
	at net.sf.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:61)
	at net.sf.cglib.proxy.Enhancer.emitMethods(Enhancer.java:911)
	at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:498)
	at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
	at net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:175)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:114)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:88)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:79)
	at org.easymock.EasyMockSupport.createMock(EasyMockSupport.java:415)

From a different location, also seemingly related to Java 8 default methods and/or lambdas.

**Comment by henri-tremblay** [comment]
*Original comment author:* Henri Tremblay

---------------------------------------------------------
Ok. I was able to reproduce with File.class.

A workaround seems to be to exclude cglib-nodep and add this:

{code:xml}
    <dependency>
      <groupId>cglib</groupId>
      <artifactId>cglib</artifactId>
      <version>3.1</version>
    </dependency>
    <dependency>
      <groupId>org.ow2.asm</groupId>
      <artifactId>asm</artifactId>
      <version>5.0.3</version>
    </dependency>
{code}

**Comment by henri-tremblay** [comment]
*Original comment author:* Scott Carey

---------------------------------------------------------
Yeah, that workaround fixes it.  Too bad maven only supports 'excludes' and no 'includes', because I have to add that everywhere I add easymock or refactor ~30+ pom files.   Fun times.

**Comment by henri-tremblay** [comment]
*Original comment author:* Jonas

---------------------------------------------------------
We're using Ivy (not Maven), but the problem is basically the same: manually overriding dependencies is a huge hassle.
How about creating a new  Easymock version (3.3.1?), with updated dependencies? That would probably save a lot of time for a lot of people.

**Comment by henri-tremblay** [comment]
*Original comment author:* Henri Tremblay

---------------------------------------------------------
cglib-nodep was replaced by cglib and then the latest ASM version was used.

**Comment by raok1997** [comment]
I tried the workaround by excluding cglib-nodep and adding cglib:cglib:3.1 & org.ow2.asm:asm:5.0.3 , but it didn't work. I upgraded easymock to 3.3.1 and it didn't fix either. I verified the Dependency hierarchy in both cases and it looked good. Am I missing something?
![easymock_issue_exclude_and_add](https://cloud.githubusercontent.com/assets/11214430/15785481/67f65d58-2985-11e6-87d4-48f06e3041f6.png)
![easymock_issue_upgrade_to_3 3 1](https://cloud.githubusercontent.com/assets/11214430/15785482/67f87d90-2985-11e6-9ea2-55749947af95.png)

**Comment by timoxino** [comment]
Thank you for digging into the issue. Upgrade to 3.1 didn't help me either but when i tried the latest (3.2.5) version it fixed the issue.
