### ISSUE TITLE
Concurrency issue in UnorderedBehavior

### ISSUE THREAD

**Issue by henri-tremblay** [easymock/easymock#16]
*Migrated from:* CodeHaus issue EASYMOCK-5
*Original reporter:* Henri Tremblay

---------------------------------------------------------
Submitted by Serguei Khramtchenko

I got the exception below when using easymock in a thread pool and looked at the source code inside UnorderedBehavior, addExpected method. The array list is not concurrent.

Exception in thread "pool-1-thread-1"
java.util.ConcurrentModificationException
      at
java.util.AbstractList$Itr.checkForComodification(AbstractList.java:
449)
      at java.util.AbstractList$Itr.next(AbstractList.java:420)
      at
org.easymock.internal.UnorderedBehavior.addExpected
(UnorderedBehavior.java:22)
      at
org.easymock.internal.MocksBehavior.addExpected(MocksBehavior.java:41)
      at
org.easymock.internal.RecordState.times(RecordState.java:185)
      at
org.easymock.internal.RecordState.closeMethod(RecordState.java:229)
      at
org.easymock.internal.RecordState.invoke(RecordState.java:62)
      at
org.easymock.internal.MockInvocationHandler.invoke
(MockInvocationHandler.java:24)
      at
org.easymock.internal.ObjectMethodsFilter.invoke
(ObjectMethodsFilter.java:56)
      at $Proxy7.log(Unknown Source)
      at
com.casenet.core.executor.ThreadPool.beforeExecute(ThreadPool.java:62)
      at
java.util.concurrent.ThreadPoolExecutor$Worker.runTask
(ThreadPoolExecutor.java:648)
      at
java.util.concurrent.ThreadPoolExecutor$Worker.run
(ThreadPoolExecutor.java:675)
      at java.lang.Thread.run(Thread.java:595)

**Comment by henri-tremblay** [comment]
*Original comment author:* Andrei Ivanov

---------------------------------------------------------
I ran into this with 2.4, 2.5.2 and 3.0:

java.util.ConcurrentModificationException
	at java.util.AbstractList$Itr.checkForComodification(AbstractList.java:372)
	at java.util.AbstractList$Itr.next(AbstractList.java:343)
	at org.easymock.internal.UnorderedBehavior.addExpected(UnorderedBehavior.java:39)
	at org.easymock.internal.MocksBehavior.addExpected(MocksBehavior.java:62)
	at org.easymock.internal.RecordState.times(RecordState.java:185)
	at org.easymock.internal.RecordState.closeMethod(RecordState.java:226)
	at org.easymock.internal.RecordState.invoke(RecordState.java:77)
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:41)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:73)
	at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:69)
	at org.codehaus.jackson.JsonGenerator$$EnhancerByCGLIB$$fdb3cbfc.writeString(<generated>)

Can this please be reopened?

**Comment by dpinol** [comment]
Has this actually been fixed? I found the same issue with 3.4
`java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_101]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_101]
	at org.easymock.internal.UnorderedBehavior.addExpected(UnorderedBehavior.java:38) ~[easymock-3.4.jar:3.4]
	at org.easymock.internal.MocksBehavior.addExpected(MocksBehavior.java:61) ~[easymock-3.4.jar:3.4]
	at org.easymock.internal.RecordState.times(RecordState.java:192) ~[easymock-3.4.jar:3.4]
	at org.easymock.internal.RecordState.closeMethod(RecordState.java:234) ~[easymock-3.4.jar:3.4]
	at org.easymock.internal.RecordState.invoke(RecordState.java:76) ~[easymock-3.4.jar:3.4]
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:40) ~[easymock-3.4.jar:3.4]
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94) ~[easymock-3.4.jar:3.4]
	at com.sun.proxy.$Proxy90.info(Unknown Source) ~[?:?]`
