### ISSUE TITLE
andDelegateTo() does not cope with varargs

### ISSUE THREAD

**Issue by jacksonjesse** [easymock/easymock#170]
Given a method like the following in a class I am mocking:

```
public void doSomething(Object o, AnotherObject... extraObjects) {
...
}
```

And then test code that looks similar to the following:

```
myClass.doSomething(new Object(), new AnotherObject(), new AnotherObject());

EasyMock.expectLastCall().andDelegateTo(new MyClassDelegate() {
    @Override
    public void doSomething(Object o, AnotherObject... extraObjects) {
        ...
    }
});
```

I get an exception when running my tests along the lines of:

```
java.lang.IllegalArgumentException: Delegation to object [MyClassDelegate@10993713] is not implementing the mocked method [public void MyClassDelegate.doSomething(java.util.Object,AnotherObject[])]
    at org.easymock.internal.Result$1DelegatingAnswer.answer(Result.java:87)
    at org.easymock.internal.Result.answer(Result.java:106)
    at org.easymock.internal.ReplayState.invokeInner(ReplayState.java:60)
    at org.easymock.internal.ReplayState.invoke(ReplayState.java:46)
    at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:40)
    at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
    at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:97)
    ...
Caused by: java.lang.IllegalArgumentException: wrong number of arguments
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.easymock.internal.Result$1DelegatingAnswer.answer(Result.java:84)
    ... 42 more
```

From looking at the source code of `Invocation.java`, it looks like it is expanding vararg arguments into separate arguments to pass to the reflection code. However, it looks like it should really be constructing an array for the second argument.

I am running on Java 8, with EasyMock 3.3.1 and PowerMock 1.6.2.

**Comment by vbichov** [comment]
+1 with EasyMock 3.2
