### ISSUE TITLE
StackOverflowError mocking class with final equals() that calls other methods on the object

### ISSUE THREAD

**Issue by mziccard** [easymock/easymock#175]
First, thanks for the great job you are doing.

Using EasyMock 3.4. Consider the following simple example code:

``` java
package me.mziccard.example;

public class MyInt {

  private final int i;

  MyInt(int i) {
    this.i = i;
  }

  @Override
  public final boolean equals(Object obj) {
    return obj instanceof MyInt && this.get() == ((MyInt) obj).get();
  }

  public int get() {
    return i;
  }
}
```

And the following test:

``` java
package me.mziccard.example;

public class MyIntTest {

  @Test
  public void test() {
    MyInt myInt = EasyMock.createMock(MyInt.class);
    EasyMock.expect(myInt.get()).andReturn(42);
    EasyMock.replay(myInt);
    assertEquals(42, myInt.get());
    EasyMock.verify(myInt);
  }
}
```

Running the test results in the following StackOverflowError:

```
java.lang.StackOverflowError
    at java.util.ArrayList.<init>(ArrayList.java:140)
    at org.easymock.internal.Invocation.<init>(Invocation.java:44)
    at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:40)
    at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
    at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:97)
    at me.mziccard.example.MyInt$$EnhancerByCGLIB$$be69527.get(<generated>)
    at me.mziccard.example.MyInt.equals(MyInt.java:13)
    at org.easymock.internal.ExpectedInvocation.matches(ExpectedInvocation.java:85)
    at org.easymock.internal.UnorderedBehavior.addActual(UnorderedBehavior.java:57)
    at org.easymock.internal.MocksBehavior.addActual(MocksBehavior.java:87)
    at org.easymock.internal.ReplayState.invokeInner(ReplayState.java:58)
    at org.easymock.internal.ReplayState.invoke(ReplayState.java:46)
    at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:40)
    at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:94)
    at org.easymock.internal.ClassProxyFactory$MockMethodInterceptor.intercept(ClassProxyFactory.java:97)
    at me.mziccard.example.MyInt$$EnhancerByCGLIB$$be69527.get(<generated>)
    at me.mziccard.example.MyInt.equals(MyInt.java:13)
        ...
```

It might be worth noting that removing `final` from the `equals` method signature or removing the call to `get()` from the `equals` method body solves the issue.

Is this behavior somehow expected?  Any clue?

**Comment by Marty** [comment]
I ran into the same issue myself (also 3.4).
Too bad no one looked into this so far.

**Comment by henri-tremblay** [comment]
Sorry. I should have looked earlier. So, the problem is that EasyMock normally provides its own implementation for `equals`. But since the `equals` is final, it can't. So the normal `equals` is called. So normally, I would say you should remove the `final` (or I should fix EasyMock to never call equals, but that's another topic). But you have workaround.

Your `equals` implementation has two "problems":
* It is calling `get` which is a mocked method. The stackoverflow comes from there. So using directly `i` works. But it's not a real solution because a mock being a mock, `i == 0` since it hasn't been initialized. But I really prefer using direct fields in my `equals`
* Same instances should have a quick exit in an `equals`. That would improve the `equals` but also solve your problem. Just add this at the beginning of your `equals`.

```java
if(obj == this) {
    return true;
}
```

Still, I will keep this issue open because I would really like EasyMock to remove its dependency on `equals`.
