### ISSUE TITLE
easymock 3.6 can't work with JDK11 EA kit

### ISSUE THREAD

**Issue by ffang** [easymock/easymock#218]
get exception like
```
java.lang.IllegalArgumentException: Unsupported class file major version 55
	at org.easymock.asm.ClassReader.<init>(ClassReader.java:166)
	at org.easymock.asm.ClassReader.<init>(ClassReader.java:148)
	at org.easymock.asm.ClassReader.<init>(ClassReader.java:136)
	at org.easymock.asm.ClassReader.<init>(ClassReader.java:237)
	at org.easymock.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:69)
	at org.easymock.cglib.proxy.Enhancer.emitMethods(Enhancer.java:1132)
	at org.easymock.cglib.proxy.Enhancer.generateClass(Enhancer.java:630)
	at org.easymock.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.easymock.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at org.easymock.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at org.easymock.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.easymock.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at org.easymock.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at org.easymock.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at org.easymock.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at org.easymock.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:175)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:123)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:99)
	at org.easymock.EasyMockSupport.niceMock(EasyMockSupport.java:196)
```
Since easymock shade the asm code, and this issue get resolved in asm6.2, so easymock should upgrade to asm6.2 to work with jdk11.

I've built a easymock with asm6.2 locally and it works with jdk11

**Comment by ffang** [comment]
While I'm working on a PR, just found that this commit
0239816375a9b75e9b4c98978740315b5bc6dffa
already resolved it.
So now I'm looking forward to a Easymock 3.7 release.
Thanks!

**Comment by henri-tremblay** [comment]
Yes. You are right. It is already solved so I will close this issue and add it to the roadmap to 3.7. The release should not be far. ASM is shaded because it uses to clash a lot with other frameworks. However, with the new Java delivery pace, ASM is getting an upgrade every 2 seconds so it is getting hard to keep pace.

**Comment by aaime** [comment]
@henri-tremblay  I know that this kind of question is annoying, but it's October, do you know when the release will become available? (commenting on the "The release should not be far"... I know I know, open source is volunteer based and what we hope to do does not always turn into reality... just wondering).

**Comment by henri-tremblay** [comment]
@aaime I'm done with the features. I tried to deliver tonight but Android tests are currently crashing. If someone has an Android expertise, please have a look. Right now I don't know if it's the test harness or EasyMock the problem. I might also just drop it and just deliver without the Android tests.
