### ISSUE TITLE
UnsupportedOperationException testing with Java 11.0.1

### ISSUE THREAD

**Issue by garydgregory** [easymock/easymock#230]
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T12:33:14-06:00)
Maven home: C:\Java\apache-maven-3.5.4\bin\..
Java version: 11.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

- git clone master
- Run ```mvn clean package```:
```
[INFO] Running org.easymock.tests.CglibTest
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.004 s <<< FAILURE! - in org.easymock.tests.CglibTest
[ERROR] testJava8(org.easymock.tests.CglibTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.UnsupportedOperationException
        at org.easymock.tests.CglibTest.testJava8(CglibTest.java:80)
```

Checking out the ```easymock-3.6``` tag I get:
```
[INFO] Running org.easymock.tests.CglibTest
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.008 s <<< FAILURE! - in org.easymock.tests.CglibTest
[ERROR] testJava8(org.easymock.tests.CglibTest)  Time elapsed: 0.002 s  <<< ERROR!
java.lang.IllegalArgumentException: Unsupported class file major version 55
        at org.easymock.tests.CglibTest.testJava8(CglibTest.java:79)
```

I am trying this in order to look for a solution using 3.6 where I see the following building Apache Commons Configuration 2.4-RC1:

```
java.lang.IllegalArgumentException: Unsupported class file major version 55
	at org.easymock.asm.ClassReader.<init>(ClassReader.java:166)
	at org.easymock.asm.ClassReader.<init>(ClassReader.java:148)
	at org.easymock.asm.ClassReader.<init>(ClassReader.java:136)
	at org.easymock.asm.ClassReader.<init>(ClassReader.java:237)
	at org.easymock.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:69)
	at org.easymock.cglib.proxy.Enhancer.emitMethods(Enhancer.java:1132)
	at org.easymock.cglib.proxy.Enhancer.generateClass(Enhancer.java:630)
	at org.easymock.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.easymock.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at org.easymock.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at org.easymock.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.easymock.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at org.easymock.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at org.easymock.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at org.easymock.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at org.easymock.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:175)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:123)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:99)
	at org.easymock.EasyMock.mock(EasyMock.java:69)
	at org.easymock.EasyMock.createMock(EasyMock.java:311)
	at org.apache.commons.configuration2.reloading.TestFileHandlerReloadingDetector.testRefreshIsReloadingRequiredTrue(TestFileHandlerReloadingDetector.java:131)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

**Comment by garydgregory** [comment]
Where is the source for ```org.easymock.asm.ClassReader``` BTW?

**Comment by henri-tremblay** [comment]
EasyMock doesn't work no Java 11 yet. It should be delivered soon (like tonight or tomorrow). `ClassReader` comes from ASM and is shaded in EasyMock.

**Comment by garydgregory** [comment]
@henri-tremblay 
Thank you for your reply. Updating from 3.6 to 4.0, I now get:
```
java.lang.UnsupportedOperationException
	at org.easymock.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
	at org.easymock.asm.ClassReader.accept(ClassReader.java:651)
	at org.easymock.asm.ClassReader.accept(ClassReader.java:391)
	at org.easymock.cglib.core.DuplicatesPredicate.<init>(DuplicatesPredicate.java:93)
	at org.easymock.cglib.proxy.Enhancer.getMethods(Enhancer.java:557)
	at org.easymock.cglib.proxy.Enhancer.generateClass(Enhancer.java:575)
	at org.easymock.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.easymock.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at org.easymock.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at org.easymock.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.easymock.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at org.easymock.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at org.easymock.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at org.easymock.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at org.easymock.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:175)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:98)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:73)
	at org.easymock.IMocksControl.mock(IMocksControl.java:44)
	at org.easymock.EasyMock.mock(EasyMock.java:72)
	at org.easymock.EasyMock.createMock(EasyMock.java:350)
	at org.apache.commons.configuration2.reloading.TestFileHandlerReloadingDetector.testRefreshIsReloadingRequiredTrue(TestFileHandlerReloadingDetector.java:131)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```
Any ideas?
I am building https://svn.apache.org/viewvc/commons/proper/configuration/trunk/ using 
```
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T12:41:47-06:00)
Maven home: C:\Java\apache-maven-3.6.0\bin\..
Java version: 11.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11.0.1
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
This is Maven 3.6.0 RC BTW.

**Comment by henri-tremblay** [comment]
Can you try by passing `-Dnet.sf.cglib.experimental_asm7=true`? In the current ASM and CGLIB version, Java 11 is still experimental so they require a parameter to activate it. We are waiting for CGLIB to be delivered to remove that need.

**Comment by garydgregory** [comment]
Hi,

The option ```-Dnet.sf.cglib.experimental_asm7=true``` seems to make no difference:
```
java.lang.UnsupportedOperationException
	at org.easymock.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
	at org.easymock.asm.ClassReader.accept(ClassReader.java:651)
	at org.easymock.asm.ClassReader.accept(ClassReader.java:391)
	at org.easymock.cglib.core.DuplicatesPredicate.<init>(DuplicatesPredicate.java:93)
	at org.easymock.cglib.proxy.Enhancer.getMethods(Enhancer.java:557)
	at org.easymock.cglib.proxy.Enhancer.generateClass(Enhancer.java:575)
	at org.easymock.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.easymock.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
	at org.easymock.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at org.easymock.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.easymock.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	at org.easymock.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.easymock.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at org.easymock.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at org.easymock.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at org.easymock.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:175)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:98)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:73)
	at org.easymock.IMocksControl.mock(IMocksControl.java:44)
	at org.easymock.EasyMock.mock(EasyMock.java:72)
	at org.easymock.EasyMock.createMock(EasyMock.java:350)
	at org.apache.commons.configuration2.reloading.TestFileHandlerReloadingDetector.testRefreshIsReloadingRequiredTrue(TestFileHandlerReloadingDetector.java:131)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

**Comment by henri-tremblay** [comment]
Can you please try EasyMock 4.0.1? It has all the final versions. So no experimental anymore.

**Comment by garydgregory** [comment]
Using 4.0.1, I can build on Oracle Java 8, 11.0.1, and 12-ea. Thank you!
