### ISSUE TITLE
CglibTest fails on OpenJDK 13 EA.

### ISSUE THREAD

**Issue by garydgregory** [easymock/easymock#241]
CglibTest fails on OpenJDK 13 EA:
```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.018 s <<< FAILURE! - in org.easymock.tests.CglibTest
[ERROR] testJava8(org.easymock.tests.CglibTest)  Time elapsed: 0.01 s  <<< ERROR!
java.lang.IllegalArgumentException: Unsupported class file major version 57
        at org.easymock.tests.CglibTest.testJava8(CglibTest.java:80)
```
```
openjdk version "13-ea" 2019-09-17
OpenJDK Runtime Environment (build 13-ea+12)
OpenJDK 64-Bit Server VM (build 13-ea+12, mixed mode, sharing)
```
```
openjdk version "13-ea" 2019-09-17
OpenJDK Runtime Environment (build 13-ea+13)
OpenJDK 64-Bit Server VM (build 13-ea+13, mixed mode, sharing)
```

**Comment by henri-tremblay** [comment]
Interesting. Can you give me the full stack trace?

**Comment by garydgregory** [comment]
Here you go:
```
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 s <<< FAILURE! - in org.easymock.tests.CglibTest
[ERROR] testJava8(org.easymock.tests.CglibTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalArgumentException: Unsupported class file major version 57
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:184)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:152)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:273)
        at net.sf.cglib.core.DuplicatesPredicate.<init>(DuplicatesPredicate.java:93)
        at net.sf.cglib.proxy.Enhancer.getMethods(Enhancer.java:557)
        at net.sf.cglib.proxy.Enhancer.generateClass(Enhancer.java:575)
        at net.sf.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
        at net.sf.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:329)
        at net.sf.cglib.proxy.Enhancer.generate(Enhancer.java:492)
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
        at net.sf.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at net.sf.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
        at net.sf.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
        at net.sf.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
        at net.sf.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
        at net.sf.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
        at net.sf.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
        at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:175)
        at org.easymock.internal.MocksControl.createMock(MocksControl.java:98)
        at org.easymock.internal.MocksControl.createMock(MocksControl.java:73)
        at org.easymock.IMocksControl.mock(IMocksControl.java:44)
        at org.easymock.EasyMock.mock(EasyMock.java:70)
        at org.easymock.EasyMock.createMock(EasyMock.java:322)
        at org.easymock.tests.CglibTest.testJava8(CglibTest.java:80)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:55)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:137)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:107)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:83)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:158)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
```

**Comment by henri-tremblay** [comment]
Ok. It's coming from ASM. It doesn't support Java 13. So until it does (it
shouldn't take long), there's nothing we can do on our side.

**Comment by garydgregory** [comment]
It works with ASM 7.1. Please see https://github.com/easymock/easymock/pull/242

**Comment by henri-tremblay** [comment]
EasyMock master is on 7.1. Which version are you using?

**Comment by garydgregory** [comment]
I see 7.0 here: https://github.com/easymock/easymock/blob/master/core/pom.xml#L50

**Comment by henri-tremblay** [comment]
You are right. It's local code (doh!)

**Comment by garydgregory** [comment]
May we get a release with the updated dep?

Gary

**Comment by garydgregory** [comment]
Also in the stack trace I posted, not that the exception is thrown from EasyMock itself.

**Comment by henri-tremblay** [comment]
Closed by #242

**Comment by henri-tremblay** [comment]
@garydgregory Next version wasn't planned soon but since Java 13 is broken, it shouldn't be that far.

**Comment by anthraxx** [comment]
@henri-tremblay ping on a new release, this is hitting general setups nowadays. can we get a release?

**Comment by henri-tremblay** [comment]
Objenesis was released. I was expecting this week but got overwhelmed. But ASAP. Sorry for the delay

**Comment by anthraxx** [comment]
Cool, thanks for the fast response
