### ISSUE TITLE
Easymock throws java.lang.OutOfMemoryError: Java heap space trying to output large array (10MB+)

### ISSUE THREAD

**Issue by dmitry-fa** [easymock/easymock#255]
I have a method for handling byte arrays of large size (10MB+). I can mock it, no problem. But in case of failure Easymock tries to output parameters which may cause OutOfMemoryError.

The following code demonstrates the bug:

```
package easymock;

import org.junit.Assert;
import org.junit.Test;
import org.easymock.EasyMock;

public class AnalyzerTest {

    interface Handler {
        int handle(byte[] data);
    }

    @Test
    public void test() {
        Handler handlerMock = EasyMock.createMock(Handler.class);
        EasyMock.expect(handlerMock.handle(EasyMock.aryEq(new byte[10]))).andReturn(1);
        EasyMock.expect(handlerMock.handle(EasyMock.aryEq(new byte[10_000]))).andReturn(4);
        EasyMock.expect(handlerMock.handle(EasyMock.aryEq(new byte[10_000_000]))).andReturn(7);
        EasyMock.replay(handlerMock);
        Assert.assertEquals(1, handlerMock.handle(new byte[10]));
        Assert.assertEquals(4, handlerMock.handle(new byte[10_000]));
        Assert.assertEquals(7, handlerMock.handle(new byte[10_000_000 - 1]));
    }
}
```

Stack trace:
```
java.lang.OutOfMemoryError: Java heap space

    at java.util.Arrays.copyOf(Arrays.java:3332)
    at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
    at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
    at java.lang.StringBuilder.append(StringBuilder.java:136)
    at org.easymock.internal.ErrorMessage.appendTo(ErrorMessage.java:48)
    at org.easymock.internal.MocksBehavior.addActual(MocksBehavior.java:149)
    at org.easymock.internal.ReplayState.invokeInner(ReplayState.java:59)
    at org.easymock.internal.ReplayState.invoke(ReplayState.java:47)
    at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:40)
    at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:101)
    at easymock.$Proxy4.handle(Unknown Source)
    at easymock.AnalyzerTest.test(AnalyzerTest.java:22)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    ...
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)

```

The problem arises when given arguments are translated to string
org.easymock.internal.ArgumentToString.appendArgument():
```
        ...
         } else if (value.getClass().isArray()) {
            buffer.append("[");
            for (int i = 0; i < Array.getLength(value); i++) {
                if (i > 0) {
                    buffer.append(", ");
                }
                appendArgument(Array.get(value, i), buffer);
            }
            buffer.append("]");
          ...
```
As result, each byte is translated to substring of at least 9 characters "0 (byte),"
I doubt that someone wants to see large arrays converted to string. Would it make sense to limit the amount elements to be printed out? E.g. if the length exceeds 1024, then print the leading 1000 and the trailing 24 elements.

In real life, when the code is not as simple as demonstrated here, it's not so easy to detect the root cause.

**Comment by henri-tremblay** [comment]
You are right. We should not do a toString on an array.
