### ISSUE TITLE
upgrade to ASM 9.2 so that easymock can work with JDK18-EA

### ISSUE THREAD

**Issue by ffang** [easymock/easymock#277]
to aovid the error like from ASM ClassReader
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 62
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
		at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
```
Class file major version 62 stands for JDK18, and ASM 9.2 starts supporting this version

**Comment by henri-tremblay** [comment]
Closed by #278
