### ISSUE TITLE
'Invisible super type class' errors after fix for #274

### ISSUE THREAD

**Issue by cushon** [easymock/easymock#306]
I did some testing with the fix for #274 applied, and am seeing some regressions on JDK 11:

```
java.lang.IllegalStateException: Invisible super type class `foo.Bar` for class Bar$$$EasyMock$2
	at net.bytebuddy.dynamic.scaffold.InstrumentedType$Default.validated(InstrumentedType.java:1566)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default.prepare(MethodRegistry.java:520)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.toTypeWriter(SubclassDynamicTypeBuilder.java:212)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.toTypeWriter(SubclassDynamicTypeBuilder.java:203)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4050)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3734)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3986)
	at org.easymock.internal.ClassProxyFactory.createProxy([ClassProxyFactory.java:116](http://www.docjar.com/html/api/org/easymock/internal/ClassProxyFactory.java.html))
	at org.easymock.internal.MocksControl.createMock([MocksControl.java:108](http://www.docjar.com/html/api/org/easymock/internal/MocksControl.java.html))
	at org.easymock.internal.MocksControl.createMock([MocksControl.java:81](http://www.docjar.com/html/api/org/easymock/internal/MocksControl.java.html))
	at org.easymock.IMocksControl.mock([IMocksControl.java:44](http://www.docjar.com/html/api/org/easymock/IMocksControl.java.html))
	at org.easymock.EasyMock.mock([EasyMock.java:71](http://www.docjar.com/html/api/org/easymock/EasyMock.java.html))
	at org.easymock.EasyMock.createMock([EasyMock.java:323](http://www.docjar.com/html/api/org/easymock/EasyMock.java.html))
```

The affected class is package-private, and is being mocked from the same package.

This is the code path in bytebuddy that's producing the exception: https://github.com/raphw/byte-buddy/blob/cfabb90f878174b2766e69c8df4ce9d32f52ba3c/byte-buddy-dep/src/main/java/net/bytebuddy/dynamic/scaffold/InstrumentedType.java#L1565-L1566

**Comment by henri-tremblay** [comment]
I noticed that and should have tested more thoroughly. If someone knows how to fix it, that would be great.

**Comment by cubasz** [comment]
Hi Henri, are there plans to release EM 4.4 once J17 support is added? I bet this is the fix community is waiting for as companies start adopting J17. Thanks!

**Comment by henri-tremblay** [comment]
I might release today actually. A RC version of 5.0 I think. Because I still have a couple of issues.
