### ISSUE TITLE
InvocationHandler $callback field is not accessible

### ISSUE THREAD

**Issue by cushon** [easymock/easymock#320]
I did some more testing after https://github.com/easymock/easymock/commit/a8cadba55b2cffdf7fb5fa87f9bd53b2ea36c1b3, and I'm seeing a handful of remaining failures on JDK 11 related to the JPMS.

For example, when attempting to mock `java.io.PrintWriter`:

```
java.lang.reflect.InvocationHandler java.io.PrintWriter$$$EasyMock$27.$callback accessible: module java.base does not "opens java.io" to unnamed module @13526e59; did you mean --add-opens=java.base/java.io=ALL-UNNAMED
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:348)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
	at org.easymock.internal.ClassProxyFactory.getCallbackField(ClassProxyFactory.java:210)
	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:165)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:108)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:81)
```

**Comment by henri-tremblay** [comment]
I do not experience this issue. Can you please give me a full test case?

**Comment by cushon** [comment]
I'll see if I can put together a self-contained repro.

The line it's failing on is just

```
org.easymock.EasyMock.createMock(java.util.logging.Logger.class)
```

I think the culprit is that we're using `--illegal-access=deny` with JDK 11, passing `--illegal-access=permit` lets the test pass.

I think JDK 17+ will have the same issue due to https://openjdk.org/jeps/403, unless that's handled differently?

**Comment by henri-tremblay** [comment]
No. It will be the same in JDK 17. My line is thinking is that you are running everything in the module path and it's not handled correctly.

**Comment by cushon** [comment]
That test is putting the code under test, and easymock, on the regular classpath. I think the only thing on the module path is the system modules.

**Comment by cushon** [comment]
I did some more debugging and I had started testing between a8cadba55b2cffdf7fb5fa87f9bd53b2ea36c1b3 and 9728e1fa96d614c7e5e5643dd9b891db54b7da01, the issue was fixed by 9728e1fa96d614c7e5e5643dd9b891db54b7da01.

Sorry for the noise!

**Comment by henri-tremblay** [comment]
Great news.
