### ISSUE TITLE
Java.lang.RuntimeException while mocking spark JavaRDD using Easymock.createMock

### ISSUE THREAD

**Issue by bsingh212** [easymock/easymock#380]
I'm using spark 3.3.0 with EasyMock version 3.4 and PowerMock1.7.3 and tried to create the mock using EasyMock.createMock(JavaRDD.class) getting java.lang.RuntimeException
	at org.easymock.asm.MethodVisitor.visitParameter(Unknown Source)
	at org.easymock.asm.ClassReader.b(Unknown Source)
	at org.easymock.asm.ClassReader.accept(Unknown Source)
	at org.easymock.asm.ClassReader.accept(Unknown Source)
	at org.easymock.cglib.proxy.BridgeMethodResolver.resolveAll(BridgeMethodResolver.java:61)
	at org.easymock.cglib.proxy.Enhancer.emitMethods(Enhancer.java:911)
	at org.easymock.cglib.proxy.Enhancer.generateClass(Enhancer.java:498)
	at org.easymock.cglib.core.DefaultGeneratorStrategy.generate(DefaultGeneratorStrategy.java:25)
	at org.easymock.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:216)
	at org.easymock.cglib.proxy.Enhancer.createHelper(Enhancer.java:377)
	at org.easymock.cglib.proxy.Enhancer.createClass(Enhancer.java:317)
	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:175)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:113)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:94)
	at org.easymock.EasyMock.mock(EasyMock.java:69)
	at org.easymock.EasyMock.createMock(EasyMock.java:311).

But once I update easymock and powermock plugin's with latest version error got resolved, so any other alternate option or any fix will get this version itself which we are using right now?.
or any other suggestion's which help to get out this issue?.

**Comment by henri-tremblay** [comment]
What is the java version and the full error?

But if upgrade works, I won't fix it.
