### ISSUE TITLE
Matchers don`t work as expected with generic interfaces on Easymock 5.x

### ISSUE THREAD

**Issue by yogs0thot** [easymock/easymock#455]
When I try to match a method from mock whose class is an implementation of an interface with generics on Easymock 5.1.0, I receive ClassCastException when try to call a method of mock with the matcher. Have this issue only on Easymock 5.x, on Easymock 4.6 everything works fine. Have the same results when running code both on Java 8 and Java 17. Any concerns? Below is a minimal example and stack trace:
```
public class Main {
    public static void main(String[] args) {
        A<Object> mock = EasyMock.createMock(B.class);

        IArgumentMatcher matcher = new IArgumentMatcher() {
            @Override
            public boolean matches(Object o) { return false;}
            @Override
            public void appendTo(StringBuffer stringBuffer) {}
        };

        EasyMock.reportMatcher(matcher);
        mock.test(matcher);
        EasyMock.expectLastCall();
    }
    interface A<T>{
        void test(T t);
    }
    class B implements A<String>{
        @Override
        public void test(String s) { }
    }
}
```

```
Exception in thread "main" java.lang.ClassCastException: a.Main$1 cannot be cast to java.lang.String
	at a.B$$$EasyMock$1.test(Unknown Source)
	at a.Main.main(Main.java:22)```

**Comment by henri-tremblay** [comment]
This is normal. You are passing a matcher to the `test` method that is expecting a string. So you get a class cast exception.
In your example, you should do

```java
        A<Object> mock = mock(B.class);
        mock.test(anyObject());

        IArgumentMatcher matcher = new IArgumentMatcher() {
            @Override
            public boolean matches(Object o) { return false;}
            @Override
            public void appendTo(StringBuffer stringBuffer) {}
        };

        reportMatcher(matcher);
        mock.test(null);
        expectLastCall();
```

but a cuter way would be

```java
        A<Object> mock = mock(B.class);
        mock.test(not(anyObject()));
        expectLastCall(); // this line is actually not needed
```
