### ISSUE TITLE
Easymock is not compatible with JDK 22

### ISSUE THREAD

**Issue by lprimak** [easymock/easymock#547]
Hi,

Just want to let you know that EasyMock tests are not working with JDK 22.
Most likely, the shaded bytebuddy (and asm?) needs to be upgraded.
```
[INFO] Running org.apache.shiro.guice.web.PathMatchingFilterProviderTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.231 s <<< FAILURE! -- in org.apache.shiro.guice.web.PathMatchingFilterProviderTest
[ERROR] org.apache.shiro.guice.web.PathMatchingFilterProviderTest.testPostProcess -- Time elapsed: 0.229 s <<< ERROR!
java.lang.IllegalArgumentException: Could not create type
	at org.easymock.bytebuddy.TypeCache.findOrInsert(TypeCache.java:170)
	at org.easymock.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at org.easymock.internal.ClassProxyFactory.createProxy(ClassProxyFactory.java:151)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:110)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:83)
	at org.easymock.IMocksControl.mock(IMocksControl.java:44)
	at org.easymock.EasyMock.mock(EasyMock.java:70)
	at org.easymock.EasyMock.createMock(EasyMock.java:322)
	at org.apache.shiro.guice.web.PathMatchingFilterProviderTest.testPostProcess(PathMatchingFilterProviderTest.java:37)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
Caused by: java.lang.IllegalArgumentException: org.apache.shiro.web.filter.PathMatchingFilter$$$EasyMock$1 must be defined in the same package as org.easymock.internal.ClassProxyFactory
	at org.easymock.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1635)
	at org.easymock.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:118)
	at org.easymock.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:519)
	at org.easymock.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
	at org.easymock.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6325)
	at org.easymock.internal.ClassProxyFactory.lambda$createProxy$0(ClassProxyFactory.java:161)
	at org.easymock.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	... 11 more
```

Thank you

**Comment by lprimak** [comment]
Blocks https://github.com/apache/shiro/issues/1381

**Comment by lprimak** [comment]
@henri-tremblay Any ideas please?
Thank you!

**Comment by henri-tremblay** [comment]
I will ASAP. I am shading ByteBuddy and ASM because previously, not shading Cglib and ASM was causing a lot of headaches from people using the wrong version. But these frameworks are quite stable now so I probably can remove the shading.

**Comment by garydgregory** [comment]
FWIW, this is affecting Apache Commons Collections. Once this is fixed, we can test our builds on Java 22 and hopefully 23-ea.

Any guidance on a release time frame?

**Comment by henri-tremblay** [comment]
I need to finish one this and will do it. A week or two maybe.

**Comment by lprimak** [comment]
@henri-tremblay Can we get a new release pretty please?
Thank you!

**Comment by henri-tremblay** [comment]
Done. Sorry, I wanted to fix a final bug but decided to stop have you wait and did the release. I am not shading ByteBuddy and ASM anymore so it should also be easier to upgrade to new JDKs.

**Comment by garydgregory** [comment]
Hello @henri-tremblay 
Thank you for the release 👍 
I created an issue for 5.3.0 missing from Maven central #596
