### ISSUE TITLE
java.lang.NoClassDefFoundError: net/bytebuddy/TypeCache in OSGI context since 5.3.0 / missing OSGI dependency after removal of shading

### ISSUE THREAD

**Issue by sratz** [easymock/easymock#626]
Since https://github.com/easymock/easymock/issues/593 / https://github.com/easymock/easymock/commit/b128336e0c0b8e6092ae00fff972aa67dfe4b960 EasyMock cannot be used anymore in an OSGI context:

```
java.lang.NoClassDefFoundError: net/bytebuddy/TypeCache
	at org.easymock.internal.MocksControl.getClassProxyFactory(MocksControl.java:162)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:107)
	at org.easymock.internal.MocksControl.createMock(MocksControl.java:83)
	at org.easymock.IMocksControl.mock(IMocksControl.java:44)
	at org.easymock.EasyMock.niceMock(EasyMock.java:187)
	at org.easymock.EasyMock.createNiceMock(EasyMock.java:361)
    ...
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.TypeCache cannot be found by org.easymock_5.4.0
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 89 more
```

This is because now ByteBuddy is not shaded anymore, but no OSGI dependencies to it are declared in the MANIFEST.MF file:

https://github.com/easymock/easymock/blob/92e5f5963f41f4d49ef9b9fe64f95321352a8f78/core/pom.xml#L87

`Import-Package` declarations for all the needed `net.bytebuddy.*` packages need to be added.

**Comment by henri-tremblay** [comment]
You are right. Thanks for reporting

**Comment by henri-tremblay** [comment]
The strange part is that my osgi integration tests have not seend that. Do you have an explanation? I am using pax-exam to test but I am willing to improve my test suite.
